<x-app-layout>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
    <div>Dashboard</div>
</x-app-layout>
